
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bug_repro'
version: '1.0.0'

profile: 'kev_setup'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  bug_repro:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

on-run-start:
  - "{{ debug_logs() }}"